# Question 1

In [1]:
import numpy as np
arr=np.arange(2,50+1,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [2]:
l1=[]
for i in range(5):
    x=int(input())
    l1.append(x)
print(l1)
print()

l2=[]
for i in range(5):
    y=int(input())
    l2.append(y)
print(l2)
print()

arr1 = np.array(l1)
arr2 = np.array(l2)
arr3 = np.concatenate( (arr1,arr2) )
print(arr3)

2
6
5
4
1
[2, 6, 5, 4, 1]

3
9
21
13
26
[3, 9, 21, 13, 26]

[ 2  6  5  4  1  3  9 21 13 26]


In [3]:
# sorting the arrays
print(np.sort(arr3))

[ 1  2  3  4  5  6  9 13 21 26]


# Question 3

In [4]:
a = np.array([[1,2],[3,4],[6,9]])
print(a)
print(a.shape)
print(a.size)

[[1 2]
 [3 4]
 [6 9]]
(3, 2)
6


# Question 4

In [6]:
# 1-D array
a_1d = np.array([2,5,6,1,9])

# 2-D array
a_2d = a_1d[np.newaxis]

print(a_1d)
print(a_1d.shape)
print()
print(a_2d)
print(a_2d.shape)

[2 5 6 1 9]
(5,)

[[2 5 6 1 9]]
(1, 5)


# Question 5

In [7]:
sa1 = np.array([[1,2],[3,4]])
sa2 = np.array([[5,6],[7,8]])

print("Vertical Stacking")
print(np.vstack((sa1,sa2)))
print()
print("Horizontal Stacking")
print(np.hstack((sa1,sa2)))

Vertical Stacking
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stacking
[[1 2 5 6]
 [3 4 7 8]]


# Question 6

In [10]:
ar = np.array([5,6,8,5,9,10,20,10,5,8,9,20,12])
unique, freq = np.unique(ar, return_counts = True)
print("Unique Items:",unique)
print("Count:",freq)

Unique Items: [ 5  6  8  9 10 12 20]
Count: [3 1 2 2 2 1 2]
